theme = "gruvbox_dark_hard"

[editor]
rulers = [80, 100, 120]
shell = ["bash"]

[keys.insert]
C-ret = "open_below"
S-C-ret = "open_above"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
H = ["collapse_selection", "select_mode", "goto_line_start", "normal_mode"] # see also keys.select.H
L = ["collapse_selection", "select_mode", "goto_line_end", "normal_mode"] # see also keys.select.L
D = [
  "ensure_selections_forward",
  "flip_selections",
  "collapse_selection",
  "select_mode",
  "goto_line_end",
  "delete_selection",
  "normal_mode",
] # see also keys.select.D
ret = ":format" # see also keys.select.ret
S-ret = ":reflow" # see also keys.select.S-ret

[keys.select]
H = "goto_line_start" # see also keys.normal.H
L = "goto_line_end" # see also keys.normal.L
D = [
  "ensure_selections_forward",
  "flip_selections",
  "collapse_selection",
  "select_mode",
  "goto_line_end",
  "delete_selection",
] # see also keys.normal.D
ret = ":format" # see also keys.normal.ret
S-ret = ":reflow" # see also keys.normal.S-ret

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
