theme = "gruvbox_dark_hard"

[editor]
rulers = [80, 100]
shell = ["bash"]

[keys.insert]
C-ret = "open_below"
S-C-ret = "open_above"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
H = ["select_mode", "goto_line_start", "normal_mode"] # see also keys.select.H
L = ["select_mode", "goto_line_end", "normal_mode"] # see also keys.select.L
D = [
  "select_mode",
  "goto_line_end",
  "normal_mode",
  "delete_selection"
] # see also keys.select.D

[keys.select]
H = "goto_line_start" # see also keys.normal.H
L = "goto_line_end" # see also keys.normal.L
D = ["goto_line_end", "delete_selection"] # see also keys.normal.D

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
